#Robocode window sizes
#Mon Mar 23 09:59:02 CET 2026
net.sf.robocode.ui.dialog.ConsoleDialog=710,339,500,400
net.sf.robocode.ui.dialog.NewBattleDialog=534,214,850,650
net.sf.robocode.ui.dialog.PreferencesDialog=590,381,738,316
net.sf.robocode.ui.dialog.RobocodeFrame=495,188,929,703
net.sf.robocode.ui.editor.RobocodeEditor=577,233,766,613
